'use client';
import {ArrowLeft,CalendarPlus,Edit3,Images,Send,Star} from 'lucide-react';
import {useState} from 'react';
import type {MediaAsset,MediaUploadMetadata} from '@/lib/media-types';
import type {MaternityNurse} from '@/lib/nurse-types';
import {formatShort,nurseGrade} from '@/lib/v3-engine';import {scheduleStyles} from '@/lib/nurse-constants';
import {NurseAvatar} from './nurse-avatar';import {NurseGallery} from './nurse-gallery';import {NurseStatusBadge} from './nurse-status-badge';import {Button} from './ui/button';
type Tab='概览'|'服务经历'|'评价'|'档期'|'相册'|'资料 / 证书';
type Filter='all'|'profile'|'service_case'|'cooking';
export function NurseDetailView({nurse,media,onBack,onEdit,onSchedule,onRecommend,onAddSchedule,onUpload,onDeleteMedia,onUpdateMedia,onSetAvatar}:{nurse:MaternityNurse;media:MediaAsset[];onBack:()=>void;onEdit:()=>void;onSchedule:()=>void;onRecommend:()=>void;onAddSchedule:()=>void;onUpload:(files:File[],metadata:MediaUploadMetadata)=>Promise<void>;onDeleteMedia:(id:string)=>Promise<void>;onUpdateMedia:(id:string,patch:Partial<MediaAsset>)=>Promise<void>;onSetAvatar:(id:string)=>Promise<void>}){
  const [tab,setTab]=useState<Tab>('概览'),[albumFilter,setAlbumFilter]=useState<Filter>('all'),[serviceFilter,setServiceFilter]=useState<string>();const own=media.filter(x=>x.nurseId===nurse.id),cooking=own.filter(x=>x.category==='cooking').slice(0,4),headerPhotos=own.filter(x=>x.category==='service_case'||x.category==='cooking').slice(0,3);const openAlbum=(filter:Filter,serviceId?:string)=>{setAlbumFilter(filter);setServiceFilter(serviceId);setTab('相册')};
  return <div className="page-stack nurse-record"><button className="back-button" onClick={onBack}><ArrowLeft/>返回月嫂列表</button><header className="record-header nurse-record-header"><div className="profile-visuals"><div className="profile-photo-wrap"><NurseAvatar nurseId={nurse.id} name={nurse.name} media={media} className="detail-avatar nurse-avatar"/>{own.length>0&&<button onClick={()=>openAlbum('all')}><Images/>{own.length}张照片</button>}</div>{headerPhotos.length>0&&<div className="profile-photo-strip">{headerPhotos.map(x=><button key={x.id} onClick={()=>openAlbum(x.category==='cooking'?'cooking':'all')}><img src={x.thumbnailUrl??x.url} alt={x.title??'月嫂照片'} loading="lazy"/></button>)}</div>}</div><div className="nurse-hero-copy"><div><h1>{nurse.name}</h1><span className="grade">{nurseGrade(nurse)}月嫂</span></div><p>{nurse.age}岁 · {nurse.hometown} · {nurse.experienceYears}年经验 · {nurse.serviceCount}单服务</p><div className="nurse-hero-facts"><strong>¥{nurse.price26Days.toLocaleString()} <small>/ 26天</small></strong><span className="rating"><Star/>{nurse.ratings.overall}</span><span>当前 <NurseStatusBadge status={nurse.status}/></span><span>下一可排 <b>{formatShort(nurse.availableFrom)}</b></span></div></div><div className="record-actions"><Button className="primary-button" onClick={onRecommend}><Send/>推荐给客户</Button><Button variant="outline" onClick={onAddSchedule}><CalendarPlus/>新增档期</Button><Button variant="ghost" onClick={()=>openAlbum('profile')}><Images/>更换头像</Button><Button variant="ghost" onClick={onEdit}><Edit3/>编辑资料</Button></div></header><nav className="record-tabs">{(['概览','服务经历','评价','档期','相册','资料 / 证书'] as Tab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>{setTab(x);if(x==='相册'){setAlbumFilter('all');setServiceFilter(undefined)}}}>{x}</button>)}</nav><section className="tab-content">
    {tab==='概览'&&<div className="overview-grid"><main><section><h2>核心能力</h2><div className="record-tags"><div>{nurse.skillTags.map(x=><i key={x}>{x}</i>)}</div></div></section><section><h2>性格 / 工作方式</h2><div className="record-tags"><div>{nurse.personalityTags.map(x=><i key={x}>{x}</i>)}</div></div><p>{nurse.introduction}</p></section>{cooking.length>0&&<section className="featured-cooking"><header><div><h2>精选作品</h2><p>月子餐与真实服务记录</p></div><button onClick={()=>openAlbum('all')}>查看全部相册 →</button></header><div>{cooking.slice(0,3).map(x=><button key={x.id} onClick={()=>openAlbum('cooking')}><img src={x.thumbnailUrl??x.url} alt={x.title??'月子餐'} loading="lazy"/><span>{x.title}</span><small>{x.serviceRecordId?'2026年服务案例':'月子餐作品'}</small></button>)}</div></section>}<section><h2>真实评价摘要</h2>{nurse.reviews.slice(0,2).map(x=><blockquote key={x.id}>“{x.content}”</blockquote>)}</section></main><aside className="resource-status-card"><header><div><span>资源概览</span><h2>当前资源状态</h2></div><NurseStatusBadge status={nurse.status}/></header><dl><dt>当前档期</dt><dd>{nurse.schedule.find(x=>x.status==='上户中')?.customerName??'暂无上户订单'}</dd><dt>最近服务</dt><dd>{nurse.serviceHistory[0]?.city??'—'} · {nurse.serviceHistory[0]?.familyType??'—'}</dd><dt>下一可上户</dt><dd>{nurse.availableFrom}</dd><dt>综合评价</dt><dd><span className="rating"><Star/>{nurse.ratings.overall}</span></dd></dl><div className="resource-insights"><div><small>适合推荐</small><p>{nurse.skillTags.slice(0,2).join('、')}</p></div><div><small>近期口碑</small><p>{nurse.reviews[0]?.content.slice(0,38)??'暂无评价摘要'}{(nurse.reviews[0]?.content.length??0)>38?'…':''}</p></div></div><Button variant="outline" onClick={onSchedule}>查看档期中心</Button></aside></div>}
    {tab==='服务经历'&&<div className="tab-list service-history-media">{nurse.serviceHistory.map(x=>{const photos=own.filter(m=>m.serviceRecordId===x.id);return <article key={x.id}><time>{x.month}</time><div><strong>{x.city} · {x.familyType}</strong><p>服务{x.days}天 · {x.highlights.join(' / ')}</p>{photos.length>0&&<button className="case-preview" onClick={()=>openAlbum('service_case',x.id)}>{photos.slice(0,3).map(p=><img key={p.id} src={p.thumbnailUrl??p.url} alt={p.title??'案例照片'} loading="lazy"/>)}<span>查看案例照片{photos.length>3?` +${photos.length-3}`:''}</span></button>}</div><span className="rating"><Star/>{x.rating}</span></article>})}</div>}
    {tab==='评价'&&<div className="review-grid">{nurse.reviews.map(x=><blockquote key={x.id}><div><span className="rating"><Star/>{x.rating}</span><time>{x.date}</time></div><p>“{x.content}”</p></blockquote>)}</div>}
    {tab==='档期'&&<div className="tab-list">{nurse.schedule.map(x=><button key={x.id} onClick={onSchedule}><strong>{formatShort(x.start)}–{formatShort(x.end)}</strong><span className={scheduleStyles[x.status]}>{x.status}</span><small>{x.customerName??'未关联客户'}</small></button>)}</div>}
    {tab==='相册'&&<NurseGallery key={`${albumFilter}-${serviceFilter??'all'}`} nurse={nurse} media={media} initialFilter={albumFilter} serviceRecordId={serviceFilter} onUpload={onUpload} onDelete={onDeleteMedia} onUpdate={onUpdateMedia} onSetAvatar={onSetAvatar}/>}
    {tab==='资料 / 证书'&&<div className="certificate-grid">{['母婴护理师证','健康证','催乳服务培训','身份资料已核验'].map((x,i)=><article key={x}><strong>{x}</strong><span>{i<2?'2026年已核验':'资料完整'}</span></article>)}</div>}
  </section></div>;
}
