import type { PaymentRecord, ServiceOrder } from './order-types';
import { summarizeDemoPayment } from './payment';
const payment = (
  id: string,
  orderId: string,
  amount: number,
  paymentType: PaymentRecord['paymentType'],
  paidAt: string,
  paymentMethod: PaymentRecord['paymentMethod'] = 'wechat',
): PaymentRecord => ({
  id,
  orderId,
  amount,
  paymentType,
  paymentMethod,
  paidAt,
  creatorName: '王敏',
  remark: '演示收款',
  voided: false,
});
const rows: Array<Omit<ServiceOrder, 'paymentSummary'>> = [
  {
    id: 'demo-order-unpaid',
    customerId: 'chen',
    workerId: null,
    customerName: '陈女士',
    workerName: null,
    serviceType: '月嫂服务',
    status: 'pending',
    startDate: '2027-01-08',
    endDate: '2027-02-02',
    totalAmount: 16000,
    depositAmount: 3000,
    finalPaymentDueDate: '2026-12-20',
    payments: [],
    remark: '未付款演示订单',
  },
  {
    id: 'demo-order-deposit',
    customerId: 'wang',
    workerId: 'nurse_001',
    customerName: '王女士',
    workerName: '张红',
    serviceType: '月嫂服务',
    status: 'confirmed',
    startDate: '2026-11-18',
    endDate: '2026-12-13',
    totalAmount: 16000,
    depositAmount: 3000,
    finalPaymentDueDate: '2026-11-18',
    payments: [
      payment(
        'pay-deposit-1',
        'demo-order-deposit',
        3000,
        'deposit',
        '2026-09-05',
      ),
    ],
    remark: '已付定金演示订单',
  },
  {
    id: 'demo-order-partial',
    customerId: 'li',
    workerId: 'nurse_010',
    customerName: '李女士',
    workerName: '李静',
    serviceType: '育儿嫂服务',
    status: 'confirmed',
    startDate: '2026-12-03',
    endDate: '2026-12-28',
    totalAmount: 12000,
    depositAmount: 3000,
    finalPaymentDueDate: '2026-11-25',
    payments: [
      payment(
        'pay-partial-1',
        'demo-order-partial',
        1500,
        'partial',
        '2026-09-06',
      ),
    ],
    remark: '部分付款演示订单',
  },
  {
    id: 'demo-order-overdue',
    customerId: 'zhao',
    workerId: 'nurse_005',
    customerName: '赵女士',
    workerName: '周萍',
    serviceType: '月嫂服务',
    status: 'completed',
    startDate: '2026-08-01',
    endDate: '2026-08-26',
    totalAmount: 16800,
    depositAmount: 3000,
    finalPaymentDueDate: '2026-09-03',
    payments: [
      payment(
        'pay-overdue-1',
        'demo-order-overdue',
        3000,
        'deposit',
        '2026-08-01',
      ),
    ],
    remark: '服务完成但尾款逾期',
  },
  {
    id: 'demo-order-paid',
    customerId: 'gao',
    workerId: 'nurse_012',
    customerName: '高女士',
    workerName: '刘芳',
    serviceType: '月嫂服务',
    status: 'in_service',
    startDate: '2026-09-01',
    endDate: '2026-09-26',
    totalAmount: 16000,
    depositAmount: 3000,
    finalPaymentDueDate: '2026-09-01',
    payments: [
      payment('pay-paid-1', 'demo-order-paid', 3000, 'deposit', '2026-08-20'),
      payment(
        'pay-paid-2',
        'demo-order-paid',
        13000,
        'final',
        '2026-09-01',
        'bank_transfer',
      ),
    ],
    remark: '已结清演示订单',
  },
];
export const mockOrders: ServiceOrder[] = rows.map((order) => ({
  ...order,
  paymentSummary: summarizeDemoPayment(order, '2026-09-07'),
}));
